//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pruebaTecnica.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Personas
    {
        public int idPersonas { get; set; }

        [Required]
        [DisplayName("Nombre(s)")]
        public string Nombres { get; set; }

        [Required]
        [DisplayName("Apellido Paterno")]
        public string ApPaterno { get; set; }

        [Required]
        [DisplayName("Apellido Materno")]
        public string ApMaterno { get; set; }

        [Required]
        [DisplayName("Fecha de Nacimiento")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}")]
        public System.DateTime FechaNacimiento { get; set; }
        [Required]
        public string Sexo { get; set; }

        [DisplayName("Estado de Nacimiento")]
        public string EstadoNacimiento { get; set; }
        [Required]
        [DisplayName("Telefono")]
        public string Telefono { get; set; }
        [DisplayName("Dirección Actual")]
        [Required]
        public string Direccion { get; set; }
    }

}
